docs: update installation guide
cpeditor/cpeditor pull request #573
Opened 2020-08-20 15:17 UTC by IZOBRETATEL777

add .deb packages installation guide

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate)

## Type of changes

- [ ] Bug fix (changes which fix an issue)
- [ ] New feature (changes which add functionality)
- [x] Documentation (changes which modify the documentation only)
- [ ] Style change (changes which do not affect the meaning of the code: code formatting, etc.)
- [ ] Refactor (changes which affect the meaning of the code but neither fix a bug nor add a feature)
- [ ] Performance improve (changes which improve performance)
- [ ] Test (changes which add tests)
- [ ] Build (Changes that affect the build system or external dependencies)
- [ ] CI (changes to CI configuration files and scripts)
- [ ] Chore (changes which do not belong to any type above)
- [ ] Revert (revert previous changes)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/cpeditor/cpeditor/blob/master/CONTRIBUTING.md) document.
- [x] I have tested these changes locally, and this fixes the bug/the new feature behaves as the expectation.
- [x] The settings file in the old version can be used in the new version after this change.
- [x] These changes only fix a single bug/introduces a single feature. (Otherwise, open multiple Pull Requests instead, unless these bugs/features are closely related.)
- [x] The commit messages are clear and detailed. (Otherwise, use `git reset` and commit again, or use `git rebase -i` and `git commit --amend` to modify the commit messages.)
- [x] These changes don't remove an existing feature. (Otherwise, add an option to disable this feature instead, unless it's necessary to remove this feature.)
- [x] If there are changes of the text displayed in the UI, I have wrapped them in `tr()` or `QCoreApplication::translate()`.
- [ ] I have documented these changes in [CHANGELOG.md](https://github.com/cpeditor/cpeditor/blob/master/doc/CHANGELOG.md), or these changes are not notable.

2020-08-20 15:20 UTC, coder3101 requested changes

2020-08-20 15:20 UTC, coder3101 commented on doc/INSTALL.md
> +On Debian-based Linux distributions (Ubuntu, Linux Mint and etc.) you can download `.deb` package in the assets and run the command in terminal:
`and etc` doesn't seems ok? Keep it just `etc` (no full stop)

2020-08-25 04:39 UTC, coder3101 commented
@ouuan can you translate this to Chinese Readme.

2020-08-26 14:07 UTC, StudyingFather commented
> @ouuan can you translate this to Chinese Readme.

Maybe I can help to translate it.

2020-08-26 14:10 UTC, coder3101 commented
@StudyingFather Sure! For sometime ouuan will not be very active and so we want a person to help us with chinese translation.

2020-08-26 14:11 UTC, coder3101 commented
@StudyingFather I will mention you whenever, I want a translation update from your side. In order to translate, you will need Qt Linguistic Application (Source code translations) for Readme and docs, you can edit them as you wish.

2020-08-26 14:52 UTC, ouuan commented
I think it's better to start translating the website than to maintain two documents :thinking:

2020-08-26 18:11 UTC, coder3101 commented
> I think it's better to start translating the website than to maintain two documents :thinking:

Yes, this PR is last time we will translate markdowns. It will only help while translating website docs. (Stuff can be copy pasted)

2020-09-05 06:26 UTC, coder3101 approved these changes

2020-09-19 12:31 UTC, ouuan commented
We are removing the documentation in the docs directory, so cpeditor/cpeditor.github.io#56 takes over this. The translations can be moved to the website later.

2020-09-19 12:31 UTC, closed without merging