feat: improve on non-Linux UNIX platforms
cpeditor/cpeditor pull request #633
Opened 2020-10-17 16:58 UTC by ouuan

## Description

Change some `Q_OS_LINUX` to `Q_OS_UNIX`, etc.

## Motivation and Context

Now CP Editor is [in the official repository of FreeBSD 13](https://freebsd.pkgs.org/13/freebsd-amd64/cpeditor-6.6.5.txz.html).

## Checklist

- [ ] If the key of a setting is changed, the `old` attribute is updated or it is resolved in SettingsUpdater.
- [ ] If there are changes of the text displayed in the UI, they are wrapped in `tr()` or `QCoreApplication::translate()`.
- [ ] If needed, I have opened a pull request or an issue to update the [documentation](https://github.com/cpeditor/cpeditor.github.io).
- [ ] If these changes are notable, they are documented in [CHANGELOG.md](https://github.com/cpeditor/cpeditor/blob/master/CHANGELOG.md).

## Additional text

@IZOBRETATEL777 Please update the translation.

2020-10-17 17:02 UTC, coder3101 commented
Shouldn't the doc have the information that FreeBSD have CP Editor? Do you maintain it?

2020-10-17 17:06 UTC, ouuan commented
> Shouldn't the doc have the information that FreeBSD have CP Editor?

Yes, we can. That's not related to this PR, though.

> Do you maintain it?

No, I was googling "cpeditor" and found it.

2020-10-17 17:07 UTC, coder3101 commented
@ouuan Nice!

2020-10-17 20:01 UTC, coder3101 commented on src/Settings/settings.json
> +        "default": "c++ -Wall",
Is this valid for windows?

2020-10-18 00:51 UTC, ouuan commented on src/Settings/settings.json
> +        "default": "c++ -Wall",
> Is this valid for windows?

Yes.

2020-10-18 07:48 UTC, coder3101 approved these changes

2020-10-18 07:53 UTC, coder3101 commented
@IZOBRETATEL777 translations please.

2020-10-18 07:56 UTC, coder3101 commented
Did you marked it draft because of translation or you plan to add something more?

2020-10-18 07:58 UTC, ouuan commented
> Did you marked it draft because of translation or you plan to add something more?

Because of translation. (And you approved this.)

2020-10-18 08:02 UTC, coder3101 commented
> And you approved this

I approved the code. I didn't merge it and added that label so others don't merge it too

@IZOBRETATEL777 will approve it and should remove the label.

2020-10-18 08:03 UTC, ouuan commented
> I approved the code. I didn't merge it and added that label so others don't merge it too

The green button makes me want to merge. You can leave a comment if you want to approve the code.

2020-10-18 08:04 UTC, coder3101 commented
> > I approved the code. I didn't merge it and added that label so others don't merge it too
> 
> The green button makes me want to merge. You can leave a comment if you want to approve the code.

Will make sure of it next time.

2020-10-21 19:49 UTC, coder3101 approved these changes

2020-10-21 20:10 UTC, coder3101 requested changes

2020-10-21 20:10 UTC, coder3101 commented on src/Settings/PreferencesWindow.cpp
> +#ifdef Q_OS_UNIX
All macOS are UNIX.

2020-10-21 20:10 UTC, coder3101 commented on src/appwindow.cpp
> +#elif defined(Q_OS_UNIX)
UNIX isn't actually an OS, but I'll give it a pass since there isn't anything else we can put there.

2020-10-21 20:17 UTC, coder3101 commented on src/Settings/PreferencesWindow.cpp
> +#ifdef Q_OS_UNIX
```suggestion
#if defined(Q_OS_UNIX) && (!defined(Q_OS_MAC))
```

2020-10-21 20:18 UTC, coder3101 commented on src/Settings/PreferencesWindow.cpp
> +#ifdef Q_OS_UNIX
```suggestion
#if defined(Q_OS_UNIX) && (!defined(Q_OS_MAC))
```

2020-10-24 06:13 UTC, coder3101 approved these changes

2020-10-24 06:14 UTC, merged