feat(Submit): Improve and add action menu
cpeditor/cpeditor pull request #681
Opened 2020-11-20 15:20 UTC by coder3101

This commit improves and add following:
1. "Submit" in Action menu
2. Shortcut for "Submit", default is <kbd>Ctrl+Alt+S</kbd>
3. Improve Submit logic, and warns when submission through old cf tool.

## Related Issues / Pull Requests
Fixes #679 and #201 

## Motivation and Context
This is minor changes to CF Tool and submission.

## How Has This Been Tested?
Arch Linux with KDE

## Screenshots (if appropriate)

## Checklist

- [x] If the key of a setting is changed, the `old` attribute is updated or it is resolved in SettingsUpdater.
- [x] If there are changes of the text displayed in the UI, they are wrapped in `tr()` or `QCoreApplication::translate()`.
- [x] If needed, I have opened a pull request or an issue to update the [documentation](https://github.com/cpeditor/cpeditor.github.io).
- [x] If these changes are notable, they are documented in [CHANGELOG.md](https://github.com/cpeditor/cpeditor/blob/master/CHANGELOG.md).

## Additional text
In future we will re-write submission logic, till then either this PR gets merged or updated to reflect the changes.

2020-11-21 11:09 UTC, ouuan requested changes
1. I don't like the "create when needed" logic. I'd rather show it when needed and hide it when not available.

2. I remember that CF Tool fails to submit to URLs with problem code "0" which is in the URL when you enter a running contest, which is the reason I parsed the URL for CF Tool 1.0. I think we can pass the URL to CF Tool only when we failed to parse the URL.

2020-11-21 11:09 UTC, ouuan commented on src/mainwindow.cpp
> +    if (submitToCodeforces)
```suggestion
    if (canSubmitSolution())
```

Reuse codes when possible.

2020-11-21 11:09 UTC, ouuan commented on ui/appwindow.ui
> +    <string>Ctrl+Alt+S</string>
```suggestion
    <string notr="true">Ctrl+Alt+S</string>
```

2020-11-21 12:29 UTC, coder3101 commented on CHANGELOG.md
> +-  	Fixed an issue where some URL was not being parsed by CF Tool. (#679 and #681)
```suggestion
-   Fixed an issue where some URL was not being parsed by CF Tool. (#679 and #681) 
```

2020-11-21 12:52 UTC, coder3101 commented
> I remember that CF Tool fails to submit to URLs with problem code "0" which is in the URL when you enter a running contest, which is the reason I parsed the URL for CF Tool 1.0. I think we can pass the URL to CF Tool only when we fail to parse the URL.

Yup, I see it is still open.
https://github.com/xalanq/cf-tool/issues/79

What about this solution instead. 

If url ends with "0" we make it "A" and submit with that new modified url.

2020-11-21 14:20 UTC, ouuan commented on src/Extensions/CFTool.cpp
> +    QString urlCopy = url;
Declare it when it's used, and give it a meaningful name like `convertedUrl`.

2020-11-22 12:20 UTC, coder3101 commented
@ouuan Anythine else you want me to update in this PR?

2020-12-12 16:40 UTC, ouuan requested changes
`MainWindow::cftoolPath`, `CFTool::problemContestId`, and `CFTool::problemCode` are not properly initialized, which resulted in 1. always show "CF Tool not installed" warning 2. empty contest ID and problem code in the toast message. You need to test it thoroughly.

However, my suggestion is to wait for #212. You can keep the action in the menu and hotkey part and revert the CF Tool updates. If you still want to update the CF Tool logic, you need to WELL-TEST it.

2021-02-06 16:10 UTC, coder3101 commented
After this code makes to beta, the next alpha/master will have a commit where we will completely drop the support for CF Tool < 1.0 because of the following:

1. CF Tool 0.x.x were all beta and prone to breaking changes. 1.0 should be considered at least API/cmd stable.
2. To avoid having legacy code to Parse URL which can change any day from CF, isn't actually our issue, any such changes should be delegated to CF Tool.

As a result of above, this commit adds a warning to the user that they need to update cf tool to 1.0 or above, as in future release we will not support it.

2021-02-07 14:58 UTC, ouuan commented
>     empty contest ID and problem code in the toast message.

Haven't read the code yet. But this problem remains.

2021-02-07 15:45 UTC, coder3101 commented
Sure! I will fix it.

2021-02-10 14:21 UTC, coder3101 commented
> > empty contest ID and problem code in the toast message.
> 
> Haven't read the code yet. But this problem remains.

Fixed. Please review now!

2021-02-10 14:32 UTC, coder3101 commented on src/Extensions/CFTool.cpp
> +            convertedUrl = url.mid(0, url.size() - 1) + "A";
```suggestion
            lastUrl = convertedUrl = url.mid(0, url.size() - 1) + "A";
```

2021-02-10 14:34 UTC, coder3101 commented on src/Extensions/CFTool.cpp
> +    // @coder3101: Please delete this branch when CFTool < 1.0 is no longer supported.
```suggestion
    // @coder3101: Please delete this branch and wasProblemCodeChanged, when CFTool < 1.0 is unsupported.
```

2021-02-10 14:39 UTC, coder3101 commented on src/appwindow.cpp
> +    ui->actionSubmit->setEnabled(tmp->canSubmitSolution());
```suggestion
    ui->actionSubmit->setVisible(tmp->canSubmitSolution());
```

2026-04-05 14:19 UTC, closed without merging