chore(Changelog): Press Esc to cancel selected text
cpeditor/cpeditor pull request #841
Opened 2021-05-23 13:10 UTC by coder3101

## Description

## Related Issues / Pull Requests

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate)

## Checklist

- [ ] If the key of a setting is changed, the `old` attribute is updated or it is resolved in SettingsUpdater.
- [ ] If there are changes of the text displayed in the UI, they are wrapped in `tr()` or `QCoreApplication::translate()`.
- [ ] If needed, I have opened a pull request or an issue to update the [documentation](https://github.com/cpeditor/cpeditor.github.io).
- [ ] If these changes are notable, they are documented in [CHANGELOG.md](https://github.com/cpeditor/cpeditor/blob/master/CHANGELOG.md).

## Additional text

2021-05-23 13:10 UTC, coder3101 commented on CHANGELOG.md
> +-   Press Esc key to cance selected text. (#786)
```suggestion
-   Press Esc key to cancel selected text. (#786)
```

2021-05-23 13:32 UTC, sonulohani reviewed
The changes for esc key to cancel selection was in another repositories. Do we still add the changes in changelog here. I think the appropriate changes was to show one time dialog when F11 is pressed.

2021-05-26 12:01 UTC, coder3101 commented
> The changes for esc key to cancel selection was in another repositories. Do we still add the changes in changelog here. I think the appropriate changes was to show one time dialog when F11 is pressed.

The issue for that request was raised on this repository. So we have to add to change log so users know that it has been fixed.

2021-05-26 12:07 UTC, coder3101 commented
This was better suited for `Changed` section of Changelog.

2021-05-26 12:29 UTC, sonulohani submitted a review, later dismissed

2021-05-29 11:53 UTC, ouuan requested changes

2021-05-29 11:53 UTC, ouuan commented on CHANGELOG.md
> +-   Esc key now cancels selected text, F11 can be used to enter/exit full screen mode. (#786)
```suggestion
-   Esc key, which was used to exit full-screen mode, now cancels text selection. Now you can use F11 to enter/exit the full-screen mode. (#786)
```

2021-05-29 11:53 UTC, ouuan commented on CHANGELOG.md
>  -   Fix text selection color when Dark Fusion is selected. (#788)
```suggestion
-   Fix text selection color when Dark Fusion is selected. (#788)
-   Now entering/exiting the full-screen mode outside of CP Editor (via the OS/DE/WM) is correctly handled. (#833)
```

2021-05-29 11:59 UTC, ouuan approved these changes

2021-05-29 14:17 UTC, sonulohani approved these changes

2021-05-29 14:17 UTC, merged

2021-06-09 02:49 UTC, ouuan commented
@allcontributors add @sonulohani for review